services:
  bitcanna:
    image: goldenratiostaking/goldenseed:latest
    environment:
      - ID=bitcanna-1
      - SEEDS=
    ports:
      - 16222:16222
    restart: always
  
  chihuahua:
    image: goldenratiostaking/goldenseed:latest
    environment:
      - ID=chihuahua-1
      - SEEDS=
    ports:
      - 16183:16183
    restart: always
    
  cerberus:
    image: goldenratiostaking/goldenseed:latest
    environment:
      - ID=cerberus-chain-1
      - SEEDS=
    ports:
      - 16184:16184
    restart: always
    
  cosmos:
    image: goldenratiostaking/goldenseed:latest
    environment:
      - ID=cosmoshub-4
      - SEEDS=
    ports:
      - 16181:16181
    restart: always

  dig:
    image: goldenratiostaking/goldenseed:latest
    environment:
      - ID=dig-1
      - SEEDS=
    ports:
      - 16185:16185
    restart: always

  emoney:
    image: goldenratiostaking/goldenseed:latest
    environment:
      - ID=emoney-3
      - SEEDS=
    ports:
      - 16186:16186
    restart: always
  
  evmos:
    image: goldenratiostaking/goldenseed:latest
    environment:
      - ID=evmos_9001-2
      - SEEDS=
    ports:
      - 16187:16187
    restart: always
    
  juno:
    image: goldenratiostaking/goldenseed:latest
    environment:
      - ID=juno-1
      - SEEDS=
    ports:
      - 16188:16188
    restart: always

  nom:
    image: goldenratiostaking/goldenseed:latest
    environment:
      - ID=nomic-stakenet-2
      - SEEDS=
    ports:
      - 26656:26656
    restart: always
    
  osmo:
    image: goldenratiostaking/goldenseed:latest
    environment:
      - ID=osmosis-1
      - SEEDS=
    ports:
      - 16190:16190
    restart: always  
    
    
  
